### ISSUE TITLE
How do i provide more than 3 options for checkbox selection ?

### ISSUE THREAD

**Issue by jpca999** [ataomega/react-native-multiple-select-list#2]
this code isnt working. 

    render() {
      const userList = {
        "123":"Tom",
        "124":"Michael",
        "125":"Christin2",
        "126":"Christin3",
        "p1":"RedPriority",
        "p2":"Continue",
        "p3":"Later",
        "p4":"Hola",
        "p5":"Continue",
        "p6":"Save-ontinue",
        "p7":"Continue",
        "p8":"Continue",
        "p9":"Continue",
        "p10":"Christin"
      }

      const { params } = this.props.navigation.state;
      console.log('23- PriorityScreen  =', this.props );
      return (
        <CustomMultiPicker
      options={userList}
      search={true} // should show search bar?
      multiple={true} //
      placeholder={"Search-2"}
      placeholderTextColor={'#757575'}
      returnValue={"label"} // label or value
      callback={(res)=>{ console.log(res) }} // callback, array of selected items
      rowBackgroundColor={"#eee"}
      rowHeight={40}
      rowRadius={5}
      iconColor={"#00a2dd"}
      iconSize={30}
      selectedIconName={"ios-checkmark-circle-outline"}
      unselectedIconName={"ios-radio-button-off-outline"}
      scrollViewHeight={130}
      selected={[1,2]} // list of options which are selected by default
    />
      );
    }
}

**Comment by cerberusv2px** [comment]
Please elaborate your problem.
