### ISSUE TITLE
Cannot read property 'oneOf' of undefined

### ISSUE THREAD

**Issue by pavinthan** [ataomega/react-native-multiple-select-list#8]
ExceptionsManager.js:65 Module AppRegistry is not a registered callable module (calling runApplication)
handleException @ ExceptionsManager.js:65
handleError @ InitializeCore.js:106
reportFatalError @ error-guard.js:46
__guard @ MessageQueue.js:271
MessageQueue.callFunctionReturnFlushedQueue @ MessageQueue.js:107
(anonymous) @ debuggerWorker.js:72
ExceptionsManager.js:73 Unhandled JS Exception: Cannot read property 'oneOf' of undefined
reactConsoleErrorHandler @ ExceptionsManager.js:73
logToConsole @ RCTLog.js:48
logIfNoNativeHook @ RCTLog.js:31
__callFunction @ MessageQueue.js:306
(anonymous) @ MessageQueue.js:108
__guard @ MessageQueue.js:269
MessageQueue.callFunctionReturnFlushedQueue @ MessageQueue.js:107
(anonymous) @ debuggerWorker.js:72
ExceptionsManager.js:73 Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by nikhilninawe** [comment]
Any solution for this?

**Comment by mallelapavank** [comment]
Looks like PropTypes issue. If you have upgraded your React Native it upgrades React version too. In the newer versions of React starting with React 16 I think, PropTypes has been moved to a separate package. 

**Try this:**
Replace `import { PropTypes } from 'react';` with `import PropTypes from 'prop-types';` in the following files..
`create-icon-set.js`
`tab-bar-item-ios.js`
`toolbar-android.js`
`icon-button.js`
(you can find these files in `yourapp\node_modules\react-native-multiple-select-list\node_modules\react-native-vector-icons\lib\`)

don't forget to do `npm install prop-types` if you haven't already.

**Comment by pavinthan** [comment]
@mallelapavank this package still import `PropTypes` from `react` that is the issue

**Comment by mallelapavank** [comment]
@pavinthan yes it imports `PropTypes` from `react` but it is never used in that file.

**Comment by pavinthan** [comment]
@mallelapavank please create a pull request to fix it

**Comment by mallelapavank** [comment]
Pull request [merged](https://github.com/ataomega/react-native-multiple-select-list/pull/10)

**Comment by pavinthan** [comment]
Thanks @mallelapavank
